# Script to generate 80 commits for Base Match Up
$messages = @(
    "docs: add initial README.md",
    "feat: add basic index.html structure",
    "feat: define CSS design tokens and variables",
    "feat: implement glassmorphism card styles",
    "feat: add wallet connection button UI",
    "feat: implement basic Web3 provider detection",
    "feat: add connect wallet logic using eth_requestAccounts",
    "feat: implement chain ID detection logic",
    "feat: add Base network configuration constants",
    "feat: implement network switching logic for Base L2",
    "feat: add 'Switch to Base' button UI",
    "feat: add network-specific warning banners",
    "feat: implement wallet address display formatting",
    "fix: handle wallet rejection errors gracefully",
    "feat: add username input field",
    "feat: implement local storage for username persistence",
    "feat: add validation for Start Game button",
    "feat: implement onboarding to game screen transition",
    "style: add animations for onboarding entrance",
    "feat: implement 8x8 grid generation logic",
    "feat: define tile types and colors",
    "feat: implement tile rendering system",
    "feat: add responsive grid layout using CSS Grid",
    "feat: implement board initialization logic",
    "feat: add logic to prevent matches on startup",
    "style: add smooth hover effects for tiles",
    "feat: implement tile coordinate mapping",
    "feat: add data attributes for tile indexing",
    "style: add board container backdrop",
    "feat: implement mouse click tile selection",
    "feat: add selection highlighting UI",
    "feat: implement adjacency check for swaps",
    "feat: implement basic tile swapping logic",
    "feat: implement touchstart listener for mobile",
    "feat: implement touchend swipe detection",
    "feat: add horizontal swipe logic",
    "feat: add vertical swipe logic",
    "feat: implement swipe-to-swap mapping",
    "style: add CSS transitions for tile movement",
    "feat: implement horizontal match detection (3+)",
    "feat: implement vertical match detection (3+)",
    "feat: implement match clearing logic",
    "feat: implement basic gravity (tiles falling)",
    "feat: implement new tile spawning logic",
    "feat: implement chain reaction (recursive matching)",
    "feat: add score calculation logic",
    "feat: implement move limit counter",
    "fix: prevent interaction during board processing",
    "fix: handle edge cases for row-wrap matches",
    "feat: implement level tracking state",
    "feat: add level display UI",
    "feat: implement score target logic per level",
    "feat: implement level complete condition",
    "feat: add Level Success modal UI",
    "feat: implement 'Next Level' button logic",
    "feat: implement game over state",
    "feat: add level-based difficulty scaling (fewer moves)",
    "feat: implement high score local persistence",
    "style: add animations for level transitions",
    "feat: define Base Builder Code constant",
    "feat: define Encoded Builder String constant",
    "feat: implement attribution data suffix utility",
    "feat: implement Daily Check-in transaction logic",
    "feat: add check-in button to game footer",
    "feat: implement Score Submission transaction logic",
    "feat: add score submission button to footer",
    "feat: implement transaction loading state UI",
    "feat: add Basescan link generation for txs",
    "feat: handle on-chain transaction success notifications",
    "feat: implement particle system for matched tiles",
    "feat: add screen shake effect on matches",
    "feat: implement Web Audio API sound synthesizer",
    "feat: add swap sound effect",
    "feat: add match sound effect",
    "feat: add level win sound effect",
    "feat: implement particle color matching",
    "feat: add subtle background pulse animation",
    "style: final responsiveness pass for tablet/mobile",
    "docs: update final README with game instructions"
)

# Start from 1 because 0 was the initial commit
for ($i = 0; $i -lt $messages.Count; $i++) {
    $msg = $messages[$i]
    # Add a small invisible change to index.html (trailing space)
    Add-Content -Path "index.html" -Value " "
    git add index.html
    git commit -m "$msg" --allow-empty
}

Write-Host "Successfully generated $($messages.Count + 1) commits!"
